### PR TITLE
Add jexplain - like Test::More::explain but strips json types first

### PR DESCRIPTION
**Pull request by wolfsage**

### CODE REVIEW

**Comment by rjbs** [comment]
I want this, but I think we might as well do better in at least two ways. Tell me what you think:

1. do something better than explain so that we can see type data as annotations, and so we dump true/false usefully
2. make it way easier to get this from jcmp_deeply, like making it default on fail, or a simple argument in 4th position or something

**Comment by wolfsage** [comment]
Yes on both accounts!

**Comment by rjbs** [comment]
Argh, I know I wrote code on this.  But where is it?

**Comment by rjbs** [comment]
Closed in favor of #7

**Pull request closed without merging**
